### ISSUE TITLE
Error while adding the plugin

### ISSUE THREAD

**Issue by karnamonkster** [riclolsen/scadavis-synoptic-panel#1]
Hello,
My setup is Grafana v 5.1.3
I am able to install the plugin successfully by the alternate method i.e. git clone ...
But when i try to add the panel on the dashboard, i don't see the panel and there is an error message.

![error_scadavis](https://user-images.githubusercontent.com/5524898/47263248-a9cf6580-d50e-11e8-8eec-14ab474a231d.JPG)

Is this to do with some files which need to be compiled or permission related issues?
Please help

**Comment by riclolsen** [comment]
Hi there!
Sorry, the code for the plugin is really new, it sure needs more testing.
Please check the F12 Network panel for the error in loading the synopticapi.js file.
Probably it is related to some cross-origin error.
Also, what type of web server do you have (apache, nginx, etc.)?

**Comment by karnamonkster** [comment]
I get an error : 
```
Plugin component error Error: Failed to fetch
  Instantiating https://scadavis.io/synoptic/synopticapi.js
  Loading https://grafanaIPaddress/public/plugins/scadavis-synoptic-panel/scadavis_ctrl.js
  Loading plugins/scadavis-synoptic-panel/module
```

Grafana server(v5.1.3) is running behind NGINX 
OS - CentOS 7

**Comment by rajas837** [comment]
@riclolsen & @karnamonkster ,

I got the same plugin error, any idea how to resolve?

Thanks

**Comment by riclolsen** [comment]
I have tested with Grafana 6.4.4 on Centos 7. I installed the plugin via command line
  sudo grafana-cli plugins install scadavis-synoptic-panel
It works.
This error line 
   "Loading https://grafanaIPaddress/publ..."
appears to be a problem as _grafanaIPaddress_ is not a valid site address.
Try also to enable the standard port 3000 and access Grafana directly (using this port you bypass Nginx).

**Comment by smartcuc** [comment]
Well I have Grafana 6.4.4 on Debian Stretch as Google VM and it keeps loading and loading and.. . At the end, it's not working for me.

**Comment by riclolsen** [comment]
Hi @smartcuc ,
Can you please inform the method of installation and provide the error messages you find on the F12 Developer Tools / Network / Console of the browser.
Are you accessing via some webserver or directly on port 3000?

**Comment by smartcuc** [comment]
Solved with installing a reverse proxy.

**Comment by riclolsen** [comment]
This is probably because SVG files must be served with cross-origin headers.
Access-Control-Allow-Origin: *
