### ISSUE TITLE
Error with crypto.randomUUID

### ISSUE THREAD

**Issue by Danilorivas** [riclolsen/scadavis-synoptic-panel#11]
I have tried to implement your plugin in grafana 10.2.2 but I have not succeeded. The plugin installs normally but when creating a panel the image does not load, either by loading directly or by providing a link, not even the test image that comes by default. At the top of the panel the error "crypto.randomUUID is not a function" appears. Searching I found that the error is probably due to the version of NodeJS, but I still can't solve it.

**Comment by Diemon-zp** [comment]
Same error for me. Latest Grafana version.

**Comment by ritchiecarroll** [comment]
Hi @riclolsen, I am getting same error as well. Is there a newer build I can try?

**Comment by riclolsen** [comment]
Hi!

Please try using an up-to-date browser.

Check compatibility with Crypto API here

    https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

**Comment by Danilorivas** [comment]
Hi! Thanks for the reply.
I've tried with Google Chrome version 122.0.6261.95 and I still have the same response.

**Comment by riclolsen** [comment]
Hi Danilo,

I see the problem now, the crypto.randomUUID browser API is only available for https context, if your server is http only it will cause this error. 
I will have to update the plugin to fix this problem, it will take some time.

**Comment by riclolsen** [comment]
The plugin has been updated with fixes, zip file published in the releases section.
It will be submitted to Grafana for official publishing.

**Comment by Danilorivas** [comment]
The update has worked, now I can load images correctly.
Thank you!
