### ISSUE TITLE
Grafana v6.2.1 cannot show strings

### ISSUE THREAD

**Issue by execcr** [riclolsen/scadavis-synoptic-panel#2]
Hi, i've just installed the lastest version of grafana and the plugin.
I have a problem to show strings with influxdb backend. In Inkscape i create a new text %s
with this settings:
{"align":"Right","attr":"get","tag":"TAG1","type":"Data"}

But the text in grafana stay blank.
If i change the query to load a numerical value the valus is correctly displayed.
Any hint?

**Comment by riclolsen** [comment]
Hi,
String values for tags are not yet supported. This is a planned feature for a future release.
Regards,
Ricardo
