### ISSUE TITLE
setting color on model driven tags

### ISSUE THREAD

**Issue by ajaywazir** [riclolsen/scadavis-synoptic-panel#6]
Hi
I have a grouped object
The FacePlace is DPM=DPM1
I have one Text Tag with Get
Tag set to  %DPM EXPORT_KW

The value is rendered correctly

If I add color mapping in Tag/Limit/ColorName 
as follows
%DPM EXPORT_KW   10  red

The entire group is hidden and not rendered in SCADAVis at all.
Do you have any idea?

Ajay

**Comment by riclolsen** [comment]
Can you please send the SVG file?

**Comment by ajaywazir** [comment]
Hi 
Here is the file
Thanks

Ajay

[UtilitiesEnergy.zip](https://github.com/riclolsen/scadavis-synoptic-panel/files/4599690/UtilitiesEnergy.zip)

**Comment by riclolsen** [comment]
You are using Faceplate to group measurements, this is ok.
But you must have one variable for each measurement.
What you did is:
Faceplate
Variable Value
DPM = J1

Variables should be 1 char length lower case like n, m, p...
Probably you need:
Faceplate
Variable Value
c = device_J1_connected (tags must match here with data source) 
e = J1_Ep
p = J1_P
q = J1_Q
... and so on ...

In the measurement you need
Get
Tag 
%p

Color
Tag  Limit Color
%c  false grey
%p 0 white

Watch out for number formatting, it should use printf or D3 conventions.
Variables should be used in objects 1 level inside the group where Faceplate is defined (I think this is ok in the file).

**Comment by ajaywazir** [comment]
Hi
I tried all permutations and combinations.
Still does not seem to work
here is a truncated file

[DPM.zip](https://github.com/riclolsen/scadavis-synoptic-panel/files/4600546/DPM.zip)

**Comment by riclolsen** [comment]
I need to know what are the data source tags from Grafana related to your example file.

**Comment by riclolsen** [comment]
Assuming tags for data sources.
"DB1 KWH_DELIVERED"
"DB1 EXPORT_KW"
"DB1 EXPORT_KVAR"

Here is the example file.
For other data source tags, just change in Faceplate|Value.

[DPM.zip](https://github.com/riclolsen/scadavis-synoptic-panel/files/4600732/DPM.zip)

**Comment by ajaywazir** [comment]
Thanks
