### ISSUE TITLE
Visualization not working with InfluxDB V2.0

### ISSUE THREAD

**Issue by felipepardo87587** [riclolsen/scadavis-synoptic-panel#7]
Hi!

First of all, Great piece of software" I've used it with Influxdb V1.7 succesfully and have created some great dashboards. Thank you!

I recently installed InfluxDB V2.0 (beta) and I'm using the Flux (InfluxDB) [BETA] Datasource plugin. I tried to use the Scadavis plugin with grafana but could not get the tags to work. I uploaded the SVG and can see the non-animated parts.

I tried the following Flux query:
FinalOutput = ["_field", "_time", "_value"]

RawSeries = from(bucket: "b1")
  |> range($range)  |> limit(n:1000)  
  |> filter(fn: (r) => r["_measurement"] == "nws")
  |> filter(fn: (r) => r["_field"] == "al_ct_h")
  |> filter(fn: (r) => r["eq_code"] == "OUT_1")
  |> filter(fn: (r) => r["plant_id"] == "col004")
NamedSeries = RawSeries
    |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r.title}))
    |> keep(columns:FinalOutput)
    |> set(key: "_field", value: "al_ct_H")

NamedSeries |> yield()

If I use a graph plugin different from Scadavis I see the labels displayed correctly on the lines , but when I try to use a (previously tested) SVG it simply does not show the animation.

**Comment by riclolsen** [comment]
Have you only changed the InfluxDB version?
Did Grafana, SCADAvis plugin, the SVG file and Flux datasource not changed at all?
Check the case of data names, it must match perfectly with tags in the SVG file.
You can also try to use the latest SCADAvis plugin (1.0.4) and apply the orderly tag names @1 (for the first metric), @2 (for the second metric), @3 ...

**Comment by felipepardo87587** [comment]
Influx DB Version: "version": "2.0.0-beta.9
Grafana: Version 6.7.3 (a04ef6cefc)
Scadavis Plugin version is 1.0.4
I checked and the names are correct (case too), I am testing the SVG against another installation of Influx V1.7 so I know it works. 
i tried with @ names and I see the @1, @2 values change in the table below the Panel, but still no animation whatsoever from the SVG

**Comment by riclolsen** [comment]
This is very unexpected. I have no clue. 
It will be necessary for me to install InfluxDB 2 Beta to reproduce the problem.
I will need to find some free time to do this.

**Comment by felipepardo87587** [comment]
I hear you! I often find it hard to find the time these days

If it helps, I have it all running in a Google VM, I believe I could give you access to my test setup so you can test there, so you don't have to start from scratch. 
Would Grafana and Influx passwords be enough or do you need to SSH to the VM as well? I think I could do that too.

**Comment by riclolsen** [comment]
This is ok, just Grafana web access should be enough. Send me the credentials to olsen.ricardo@gmail.com.
