### ISSUE TITLE
Error! [5] with Node-red

### ISSUE THREAD

**Issue by Joaocara** [riclolsen/scadavis-synoptic-panel#8]
Hello!
I am using the Scadavis Synoptic IO panel with Node-red and everything is working just fine, except I have a error message on the top right corner of my uibuilder display saying "Error! [5]".
How can I get rid of this error?
Thank you for the attention!
<img width="90" alt="error" src="https://user-images.githubusercontent.com/31019304/153404915-19925b51-39a9-4165-bb37-a2a9d267013b.png">

**Comment by riclolsen** [comment]
Hello João!
There is some error on the SVG file markup.
You can mouse over the error message to see more details.
If you can not solve the problem, send me the file here or on Linkedin https://www.linkedin.com/in/ricardo-olsen/.

**Comment by Joaocara** [comment]
Thank you for the answer! I got it working now.
I do have another question tho, how can I run my SCADA without internet? I already brought the https://scadavis.io/synoptic/synopticapi.js file that was used in the index.html code to my PC, but I still can't run my SCADA without internet. It only works when I am connected.

**Comment by riclolsen** [comment]
Free usage is limited to online operation, this is the way it is supposed to work.

**Comment by Joaocara** [comment]
Oh ok! Which one of the anual plans do I need to have in order to be able to use it offline?
